Python rewrite
awslabs/aws-serverless-twitter-event-source pull request #2
Opened 2018-11-28 02:03 UTC by jlhood

*Issue #, if available:* #1 

*Description of changes:*

This PR is a rewrite of this app in python. It also addresses #1 by setting tweet_mode to extended when initializing the client. There are some non-backwards-compatible changes so this will be published to SAR as a new major version (2.0.0). Those changes are:

1. Twitter API Keys are now expected to be stored in SSM Parameter Store as SecureStrings instead of passed in as encrypted or plaintext parameters to the app.
1. The previous version of the app invoked the lambda with a JSON array of tweets, but the tweets themselves were JSON strings rather than JSON data. So Lambda functions receiving the tweets would have to manually parse each tweet string as JSON rather than relying on the JSON parsing that is already done by the Lambda handler (depending on the language).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2018-11-28 21:23 UTC, paoptu023 requested changes

2018-11-28 21:23 UTC, paoptu023 commented on .vscode/settings.json
> +{
vscode configuration file probably shouldn't be included.

2018-11-28 21:23 UTC, paoptu023 commented on app/checkpoint.py
> +RECORD_KEY = 'checkpoint'
Does the DDB table only store one item - the checkpoint?

2018-11-28 21:23 UTC, paoptu023 commented on app/poller.py
> +            checkpoint.update(since_id)
https://github.com/awslabs/aws-serverless-twitter-event-source/blob/d9abb8bd3f2997a48216bde49069d7d0beaccb61/app/poller.py#L49-L50

You can move it out of the while loop, since only the last value will be kept.

2018-11-29 08:29 UTC, jlhood commented on .vscode/settings.json
> +{
I actually prefer to include it, because the settings are unique given the pipenv setup.

2018-11-29 08:29 UTC, jlhood commented on app/checkpoint.py
> +RECORD_KEY = 'checkpoint'
Yes, and only if stream mode is enabled.

2018-11-29 08:34 UTC, jlhood commented on app/poller.py
> +            checkpoint.update(since_id)
I put it in the loop on purpose so we update the checkpoint with every page we read from the Twitter API. If I don't, there can be failure modes where we keep invoking the processor with the same set of tweets over and over again. For example, if the search term returns so many results that the lambda continues to paginate and invoke the tweet processor lambda until it times out.

2018-11-29 20:16 UTC, paoptu023 approved these changes

2018-11-30 00:54 UTC, merged